apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: notification-webhook-configmap
    files:
      - notification-webhook.ini=notification-webhook.ini